#!/bin/bash

OUTPUT=""
CLIENT_RESULT1=0
CLIENT_RESULT2=0

while [[ $# -gt 0 ]]
do
    case "$1" in
        --client_result1)
        CLIENT_RESULT1=$2
        shift 2
        ;;
        --client_result2)
        CLIENT_RESULT2=$2
        shift 2
        ;;
        --output)
        OUTPUT=$2
        shift 2
        ;;
        *)
        echo "Error: invalid argument $1 of $0"
        exit
        ;;
    esac
done

DIR=`dirname $OUTPUT`
mkdir -p $DIR

echo "client_result1=$CLIENT_RESULT1">$OUTPUT
echo "client_result2=$CLIENT_RESULT2">>$OUTPUT
