#!/usr/bin/python3

import os
import sys

def get_val(filename, key):
    with open(filename) as f:
        lines = f.readlines()
    for l in lines:
        res = l.strip()
        if res:
            results = res.split(',')
            for r in results:
                k, v = r.split('=')
                k = k.strip()
                v = v.strip()
                if k == key:
                    return v
    return ''

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('usage: %s [path/to/file] [key]' % sys.argv[0])
        sys.exit()
    filename = sys.argv[1]
    key = sys.argv[2]
    if not os.path.exists(filename):
        print('Error: file %s does not exist' % filename)
        sys.exit()
    val = get_val(filename, key)
    if val:
        print('%s' % str(val))
